version: '3.4'
volumes:
  datafile:
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - datafile:/var/lib/mysql
    networks:
      static-network:
        ipv4_address: 172.20.128.2
    restart: always
  Scadenze:
    image: aspnetapp
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - "8000:80"
      - "8001:443"
    networks:
      static-network:
        ipv4_address: 172.20.128.3
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/${NOME_CERTIFICATO}.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16